package com.hgk.constants;

public interface HTMLConsts {
	String ALERT_WARNING = "alert alert-warning";
	String ALERT_DANGER = "alert alert-danger";
	String ALERT_SUCCESS = "alert alert-success";
	
	String ALERT_MSG_FOR_CORRECT_INPUT = "PLEASE ENTER CORRECT DATA !!!";
	String ALERT_MSG_FOR_DATA_ADDED_SUCCESS = "STUDENT DATA ADDED SUCCESSFULLY !!!";
	String ALERT_MSG_FOR_DATA_ADDED_FAILURE = "FAILED TO ADD STUDENT DATA !!!";
	String ALERT_MSG_FOR_DATA_EXISTS = "STUDENT DATA ALERADY EXISTS !!!";
	
	String ALERT_MSG_FOR_NAME = "PLEASE ENTER FULL NAME !!!";
	String ALERT_MSG_FOR_PERCENTAGE = "PLEASE ENTER CORRECT PERCENTAGE !!!";
	
	String ALERT_MSG_STUDENT_NOT_FOUND = "STUDENT NOT FOUND !!!";
	
	
	String ALERT_MSG_SELECT_STUDENT_TO_REMOVE = "PLEASE SELECT THE STUDENT TO REMOVE !!!";
	String ALERT_MSG_REMOVE_SUCCESS = "STUDENT REMOVED SUCESSFULLY !!!";
	String ALERT_MSG_REMOVE_FAILED = "FAILED TO REMOVE STUDENT !!!";
}
